version: '3'
services:
  mssql:
    image: 'microsoft/mssql-server-linux:2017-latest'
    hostname: 'mssql'
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SuperP4ssw0rd!
      - MSSQL_PID=Express
  sqlpad:
    image: 'sqlpad/sqlpad:latest'
    hostname: 'sqlpad'
    ports:
      - '3000:3000'
    environment:
      - SQLPAD_DEBUG=TRUE
    volumes:
      - sqlpad-volume:/var/lib/sqlpad

volumes:
  sqlpad-volume:
