version: '3.2'
services:
  sqlpad1:
      build: ./sqlpad
      tty: true
      volumes:
        - './sqlpad/src:/var/lib/sqlpad'
  sqlpad2:
      build: ./sqlpad
      tty: true
      volumes:
        - './sqlpad/src:/var/lib/sqlpad'
  sqlpad3:
      build: ./sqlpad
      tty: true
      volumes:
        - './sqlpad/src:/var/lib/sqlpad'
  nginx-lb:
      build: ./nginx-lb
      tty: true
      links:
          - sqlpad1
          - sqlpad2
          - sqlpad3
      ports:
          - '80:80'
volumes:
  backend:
